[package]
name = "wsen-pdus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = { workspace = true }

[features]
default = ["analog", "i2c"]

analog = []
i2c = []
